In [ ]:
import pandas as pd

classifica = pd.read_excel('07 - Julho.xlsx')
classifica.head()

In [ ]:
classifica.columns = classifica.iloc[1]
classifica.head()

In [ ]:
classifica.drop([0, 1], inplace=True)
classifica.info()

In [ ]:
df_clone = pd.DataFrame(classifica.loc[:, ['Tp.Visual','Talhão', 'Fardão']])
df_clone.head()

In [ ]:
def formatar_valor(valor):
    valor_str = str(valor)
    if '.' in valor_str:
        valor_formatado = "{:.3f}".format(float(valor_str.replace(',', '.')))
        return valor_formatado.replace('.', ',')
    return valor

df_clone['Fardão'] = df_clone['Fardão'].apply(formatar_valor).astype(str).str.replace(',', '').astype(int)
#df_clone.to_excel('resultado3.xlsx', index=False)
df_clone.head()

In [ ]:
df_clone['Talhão'].value_counts()

In [ ]:
'''

Talhões que já estão prontos:

1, 2, 3, 4, 05A, 05B, 6, 7, 8, 9, 10, 11, 12, 13A, 13B, 14, 15, 16, 17, 18, 19, 20, 21, 
22B, 23-24-25, 26, 27, 28, 29, 32, 33, 34, 35, 36, 37, 38, 39, 42, 43-44, 45-46
'''

# Verifica as Bordaduras

# 1	(10532-10540 e 10564 B)
df_clone.loc[
    (df_clone['Talhão'] == 1) & 
    ((df_clone['Fardão'].between(10532, 10540, inclusive='both')) 
     | (df_clone['Fardão'] == 10564)), 
    'Noite / Dia'
] = 'Bordadura'

# 3	(9937-9940 B)
df_clone.loc[
    (df_clone['Talhão'] == 3) & 
    (df_clone['Fardão'].between(9937, 9940, inclusive='both')), 
    'Noite / Dia'
] = 'Bordadura'

# 4	(11742-11746 B)
df_clone.loc[
    (df_clone['Talhão'] == 4) & 
    (df_clone['Fardão'].between(11742, 11746, inclusive='both')), 
    'Noite / Dia'
] = 'Bordadura'

# 05A	(11158-11166 B) 
df_clone.loc[
    (df_clone['Talhão'] == '05A') & 
    (df_clone['Fardão'].between(11158, 11166, inclusive='both')), 
    'Noite / Dia'
] = 'Bordadura'

# 05B	11286 e 11316 B  
df_clone.loc[
    (df_clone['Talhão'] == '05B') & 
    (df_clone['Fardão'].between(11286, 11316, inclusive='both')), 
    'Noite / Dia'
] = 'Bordadura'

# 6	1053 -1056 B
df_clone.loc[
    (df_clone['Talhão'] == 6) & 
    (df_clone['Fardão'].between(1053, 1056, inclusive='both')), 
    'Noite / Dia'
] = 'Bordadura'

# 9	 (5270-5272-B)
df_clone.loc[
    (df_clone['Talhão'] == 9) & 
    (df_clone['Fardão'].between(5270, 5272, inclusive='both')), 
    'Noite / Dia'
] = 'Bordadura'

# 10	(5013-5020 - 6338- 6340 B) 
df_clone.loc[
    (df_clone['Talhão'] == 10) & 
    ((df_clone['Fardão'].between(5013, 5020, inclusive='both')) | 
     (df_clone['Fardão'].between(6338, 6340, inclusive='both'))),
    'Noite / Dia'
] = 'Bordadura'

#11	(4798-4801 - 6341-6344 B) 
df_clone.loc[
    (df_clone['Talhão'] == 11) & 
    ((df_clone['Fardão'].between(4798, 4801, inclusive='both')) | 
     (df_clone['Fardão'].between(6341, 6344, inclusive='both'))),
    'Noite / Dia'
] = 'Bordadura'

# 12	(4501- 5099-6006 B)
df_clone.loc[
    (df_clone['Talhão'] == 12) & 
    ((df_clone['Fardão'].between(5099, 6006, inclusive='both')) 
     | (df_clone['Fardão'] == 4501)), 
    'Noite / Dia'
] = 'Bordadura'

# 13A bordadura	1918-1924
df_clone.loc[
    (df_clone['Talhão'] == '13A') &
    (df_clone['Fardão'].between(1918, 1924, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 13B	(6336-6337 B)
df_clone.loc[
    (df_clone['Talhão'] == '13B') &
    (df_clone['Fardão'].between(6336, 6337, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

#14	(8587-8592 B)
df_clone.loc[
    (df_clone['Talhão'] == 14) &
    (df_clone['Fardão'].between(8587, 8592, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 15	(8598-8606 B)
df_clone.loc[
    (df_clone['Talhão'] == 15) &
    (df_clone['Fardão'].between(8598, 8606, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 18	(7855-7877 B)
df_clone.loc[
    (df_clone['Talhão'] == 18) &
    (df_clone['Fardão'].between(7855, 7877, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 19	(7631-7654 B)
df_clone.loc[
    (df_clone['Talhão'] == 19) &
    (df_clone['Fardão'].between(7631, 7654, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 21	(2860 - 2868 B)
df_clone.loc[
    (df_clone['Talhão'] == 21) &
    (df_clone['Fardão'].between(2860, 2868, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 22B	( 1620 -1624 B)
df_clone.loc[
    (df_clone['Talhão'] == '22B') &
    (df_clone['Fardão'].between(1620, 1624, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 28	(7223-7239 B)
df_clone.loc[
    (df_clone['Talhão'] == 28) &
    (df_clone['Fardão'].between(7223, 7239, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 33	(3536 -3537 B)
df_clone.loc[
    (df_clone['Talhão'] == 33) &
    (df_clone['Fardão'].between(3536, 3537, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 34	(8310-8315 e 8342-8349 B)
df_clone.loc[
    (df_clone['Talhão'] == 34) & 
    ((df_clone['Fardão'].between(8310, 8315, inclusive='both')) | 
     (df_clone['Fardão'].between(8342, 8349, inclusive='both'))),
    'Noite / Dia'
] = 'Bordadura'

# 35	(307-311 B)
df_clone.loc[
    (df_clone['Talhão'] == 35) &
    (df_clone['Fardão'].between(307, 311, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 36	(2451 - 2454 B)
df_clone.loc[
    (df_clone['Talhão'] == 36) &
    (df_clone['Fardão'].between(2451, 2454, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 38	(4288- 4292 B)
df_clone.loc[
    (df_clone['Talhão'] == 38) &
    (df_clone['Fardão'].between(4288, 4292, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 42	241-246 B
df_clone.loc[
    (df_clone['Talhão'] == 42) &
    (df_clone['Fardão'].between(241, 246, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 43-44	(1273-1280 B)
df_clone.loc[
    (df_clone['Talhão'] == '43-44') &
    (df_clone['Fardão'].between(1273, 1280, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'

# 45-46	(6197-6198 B)
df_clone.loc[
    (df_clone['Talhão'] == '45-46') &
    (df_clone['Fardão'].between(6197, 6198, inclusive='both')),
    'Noite / Dia'
] = 'Bordadura'




# Normais
#1: 10205-10316
df_clone.loc[
    (df_clone['Talhão'] == 1) &
    (df_clone['Fardão'].between(10205, 10316, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# 2:
df_clone.loc[
    (df_clone['Talhão'] == 2),
    'Noite / Dia'
] = 'Dia'

#3	 9523-9753
df_clone.loc[
    (df_clone['Talhão'] == 3) &
    (df_clone['Fardão'].between(9523, 9753, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

#4	 11318-11417	11609-11700
df_clone.loc[
    (df_clone['Talhão'] == 4) & 
    ((df_clone['Fardão'].between(11318, 11417, inclusive='both')) | 
     (df_clone['Fardão'].between(11609, 11700, inclusive='both'))),
    'Noite / Dia'
] = 'Noite'

# 05A: 10565-10678 / 10868 -10932
df_clone.loc[
    (df_clone['Talhão'] == '05A') & 
    ((df_clone['Fardão'].between(10565, 10678, inclusive='both')) | 
     (df_clone['Fardão'].between(10868, 10932, inclusive='both'))),
    'Noite / Dia'
] = 'Noite'

# 05B 
df_clone.loc[
    (df_clone['Talhão'] == '05B'),
    'Noite / Dia'
] = 'Dia'

# 6	1173 -1198
df_clone.loc[
    (df_clone['Talhão'] == 6) &
    (df_clone['Fardão'].between(1173, 1198, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# 7: 197 - 217	
df_clone.loc[
    (df_clone['Talhão'] == 7) &
    (df_clone['Fardão'].between(197, 217, inclusive='both')),
    'Noite / Dia'
] = 'Noite'


# 8: 750 - 875	943 - 975
df_clone.loc[
    (df_clone['Talhão'] == 8) & 
    ((df_clone['Fardão'].between(750, 875, inclusive='both')) | 
     (df_clone['Fardão'].between(943, 975, inclusive='both'))),
    'Noite / Dia'
] = 'Noite'


# 9:  5021 - 5204
df_clone.loc[
    (df_clone['Talhão'] == 9) &
    (df_clone['Fardão'].between(5021, 5204, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

#10:	4806 - 5020	
df_clone.loc[
    (df_clone['Talhão'] == 10) &
    (df_clone['Fardão'].between(4806, 5020, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# 11:	4711 - 4797	
df_clone.loc[
    (df_clone['Talhão'] == 11) &
    (df_clone['Fardão'].between(4711, 4797, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

#12:	4373-4422
df_clone.loc[
    (df_clone['Talhão'] == 12) &
    (df_clone['Fardão'].between(4373, 4422, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# 13A	2456 - 2547 
df_clone.loc[
    (df_clone['Talhão'] == '13A') &
    (df_clone['Fardão'].between(2456, 2547, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

#13B: 2456 - 2547
df_clone.loc[
    (df_clone['Talhão'] == '13B') &
    (df_clone['Fardão'].between(2456, 2547, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# atualizado 14: 8428-8590            
df_clone.loc[
    (df_clone['Talhão'] == 14) &
    (df_clone['Fardão'].between(8428, 8590, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# 15
df_clone.loc[
    (df_clone['Talhão'] == 15),
    'Noite / Dia'
] = 'Dia'

# 16
df_clone.loc[
    (df_clone['Talhão'] == 16),
    'Noite / Dia'
] = 'Dia'

# 17
df_clone.loc[
    (df_clone['Talhão'] == 17),
    'Noite / Dia'
] = 'Dia'

# 18: 7881-8068
df_clone.loc[
    (df_clone['Talhão'] == 18) &
    (df_clone['Fardão'].between(7881, 8068, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

#19	7501-7629
df_clone.loc[
    (df_clone['Talhão'] == 19) &
    (df_clone['Fardão'].between(7501, 7629, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# 20
df_clone.loc[
    (df_clone['Talhão'] == 20),
    'Noite / Dia'
] = 'Dia'

#21	
df_clone.loc[
    (df_clone['Talhão'] == 21),
    'Noite / Dia'
] = 'Dia'

# 22B: 1738 - 1815        
df_clone.loc[
    (df_clone['Talhão'] == '22B') &
    (df_clone['Fardão'].between(1738, 1815, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# 23-24-25
df_clone.loc[
    (df_clone['Talhão'] == '23-24-25'),
    'Noite / Dia'
] = 'Dia'
     
# 26
df_clone.loc[
    (df_clone['Talhão'] == 26),
    'Noite / Dia'
] = 'Dia' 

#27, 26, 29
df_clone.loc[
    (df_clone['Talhão'] == 27),
    'Noite / Dia'
] = 'Dia' 

#29
df_clone.loc[
    (df_clone['Talhão'] == 29),
    'Noite / Dia'
] = 'Dia' 


#28	6875-6970
df_clone.loc[
    (df_clone['Talhão'] == 28) &
    (df_clone['Fardão'].between(6875, 6970, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# 32
df_clone.loc[
    (df_clone['Talhão'] == 32),
    'Noite / Dia'
] = 'Dia' 

# 33: 8317- 8427
df_clone.loc[
    (df_clone['Talhão'] == 33) &
    (df_clone['Fardão'].between(8317, 8427, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# atualizado 34	8317-8427 
df_clone.loc[
    (df_clone['Talhão'] == 34) &
    (df_clone['Fardão'].between(8317, 8427, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# 35: 369-436	
df_clone.loc[
    (df_clone['Talhão'] == 35) &
    (df_clone['Fardão'].between(369, 436, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# atualizado 36	3142 - 3205	  2350 - 2429
df_clone.loc[
    (df_clone['Talhão'] == 36) & 
    ((df_clone['Fardão'].between(3142, 3205, inclusive='both')) | (df_clone['Fardão'].between(2350, 2429, inclusive='both'))),
    'Noite / Dia'
] = 'Noite'

# atualizado 37	1974 - 2043  3280 - 3354        
df_clone.loc[
    (df_clone['Talhão'] == 37) & 
    ((df_clone['Fardão'].between(1974, 2043, inclusive='both')) | (df_clone['Fardão'].between(3280, 3354, inclusive='both'))),
    'Noite / Dia'
] = 'Noite'

#38:	3975 - 4054
df_clone.loc[
    (df_clone['Talhão'] == 38) & 
    (df_clone['Fardão'].between(3975, 4054, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

#39:	3878 - 3974
df_clone.loc[
    (df_clone['Talhão'] == 39) &
    (df_clone['Fardão'].between(3878, 3974, inclusive='both')),
    'Noite / Dia'
] = 'Noite'

# 43-44	1289-1308 / 1493-1568
df_clone.loc[
    (df_clone['Talhão'] == '43-44') & 
    ((df_clone['Fardão'].between(1289, 1308, inclusive='both')) | (df_clone['Fardão'].between(1493, 1568, inclusive='both'))),
    'Noite / Dia'
] = 'Noite'

# 45-46: (5746 - 5841)	(6110 - 6193)
df_clone.loc[
    (df_clone['Talhão'] == '45-46') & 
    ((df_clone['Fardão'].between(5746, 5841, inclusive='both')) | (df_clone['Fardão'].between(6110, 6193, inclusive='both'))),
    'Noite / Dia'
] = 'Noite'



df_clone.loc[
    
      #1: 10205-10316
    ~((df_clone['Talhão'] == 1) &
      (df_clone['Fardão'].between(10205, 10316, inclusive='both'))) &

      #3	 9523-9753
    ~((df_clone['Talhão'] == 3) &
      (df_clone['Fardão'].between(9523, 9753, inclusive='both'))) &

      #4	 11318-11417	11609-11700
    ~((df_clone['Talhão'] == 4) & 
      ((df_clone['Fardão'].between(11318, 11417, inclusive='both')) | 
      (df_clone['Fardão'].between(11609, 11700, inclusive='both')))) &

      # 05A: 10565-10678 / 10868 -10932
    ~((df_clone['Talhão'] == '05A') & 
      ((df_clone['Fardão'].between(10565, 10678, inclusive='both')) | 
      (df_clone['Fardão'].between(10868, 10932, inclusive='both')))) &

          # 6	1173 -1198
    ~((df_clone['Talhão'] == 6) &
      (df_clone['Fardão'].between(1173, 1198, inclusive='both'))) &

      # 7: 197 - 217	
    ~((df_clone['Talhão'] == 7) &
      (df_clone['Fardão'].between(197, 217, inclusive='both'))) &

      # 8: 750 - 875	943 - 975
    ~((df_clone['Talhão'] == 8) & 
      ((df_clone['Fardão'].between(750, 875, inclusive='both')) | 
      (df_clone['Fardão'].between(943, 975, inclusive='both')))) &

      # 9:  5021 - 5204
    ~((df_clone['Talhão'] == 9) &
      (df_clone['Fardão'].between(5021, 5204, inclusive='both'))) &

      #10:	4806 - 5020	
    ~((df_clone['Talhão'] == 10) &
      (df_clone['Fardão'].between(4806, 5020, inclusive='both'))) &

      # 11:	4711 - 4797	
    ~((df_clone['Talhão'] == 11) &
      (df_clone['Fardão'].between(4711, 4797, inclusive='both'))) &

       #12:	4373-4422
    ~((df_clone['Talhão'] == 12) &
      (df_clone['Fardão'].between(4373, 4422, inclusive='both'))) &

      # 13A	2456 - 2547  bor	1918 -1924
    ~((df_clone['Talhão'] == '13A') & 
      ((df_clone['Fardão'].between(2456, 2547, inclusive='both')) | 
      (df_clone['Fardão'].between(1918, 1924, inclusive='both')))) &
      
      #13B: 2456 - 2547
    ~((df_clone['Talhão'] == '13B') &
      (df_clone['Fardão'].between(2456, 2547, inclusive='both'))) &

      #14: 8428-8590
    ~((df_clone['Talhão'] == 14) &
      (df_clone['Fardão'].between(8428, 8590, inclusive='both'))) &

      # 18: 7881-8068
    ~((df_clone['Talhão'] == 18) &
      (df_clone['Fardão'].between(7881, 8068, inclusive='both'))) &

      #19	7501-7629
    ~((df_clone['Talhão'] == 19) &
      (df_clone['Fardão'].between(7501, 7629, inclusive='both'))) &

      # 20
    ~((df_clone['Talhão'] == 20)) &
    
      # 21	
    ~((df_clone['Talhão'] == 21)) &

      # 22B: 1738 - 1815
    ~((df_clone['Talhão'] == '22B') &
      (df_clone['Fardão'].between(1738, 1815, inclusive='both'))) &
     
      # 28	6875-6970
    ~((df_clone['Talhão'] == 28) &
      (df_clone['Fardão'].between(6875, 6970, inclusive='both'))) &
 
      # 33: 8317- 8427
    ~ ((df_clone['Talhão'] == 33) &
      (df_clone['Fardão'].between(8317, 8427, inclusive='both'))) &

      # 34	8317-8427
    ~ ((df_clone['Talhão'] == 34) &
      (df_clone['Fardão'].between(8317, 8427, inclusive='both'))) &

      # 35: 369-436
    ~ ((df_clone['Talhão'] == 35) &
      (df_clone['Fardão'].between(369, 436, inclusive='both'))) &	

      # 36	3142 - 3205	  2350 - 2429 
    ~ ((df_clone['Talhão'] == 36) & 
      ((df_clone['Fardão'].between(3142, 3205, inclusive='both')) | 
       (df_clone['Fardão'].between(2350, 2429, inclusive='both')))) &

      # 37	1974 - 2043  3280 - 3354
    ~ ((df_clone['Talhão'] == 37) & 
      ((df_clone['Fardão'].between(1974, 2043, inclusive='both')) | 
      (df_clone['Fardão'].between(3280, 3354, inclusive='both')))) &

      # 38:	3975 - 4054
    ~ ((df_clone['Talhão'] == 38) & 
      (df_clone['Fardão'].between(3975, 4054, inclusive='both'))) &

      # 39:	3878 - 3974
    ~ ((df_clone['Talhão'] == 39) & 
      (df_clone['Fardão'].between(3878, 3974, inclusive='both'))) &

      # 45-46: (5746 - 5841)	(6110 - 6193)
    ~ ((df_clone['Talhão'] == '45-46') & 
      ((df_clone['Fardão'].between(5746, 5841, inclusive='both')) | 
      (df_clone['Fardão'].between(6110, 6193, inclusive='both')))),
    'Noite / Dia'
] = 'Dia'


df_clone.head()

In [ ]:
classifica['Tp.Visual'].value_counts()

In [ ]:
""" Tipos Mapeados


32-3', '32-4', '33-3', '34-4', '42-3', '42-4', '43-4', '44-4 ', '52-5', '53-5', '54-5', '62-6', '63-6', '73-7', 'BG'

 """

result = df_clone[df_clone['Tp.Visual'].isin(['32-3', '32-4', '33-3', '34-4', '42-3', '42-4', '43-4', '44-4 ', '52-5', '53-5',     
                                               '54-5', '62-6', '63-6', '73-7', 'BG'])].groupby(['Tp.Visual', 'Talhão'])['Noite / Dia'].unique()


result_df = result.reset_index()

result_df.to_excel('resultado.xlsx', index=False)

print('Arquivo Excel salvo com sucesso!')